[server]
mode = "dev"
port = ":8080"
dbname = "order-system"
host = "mongodb://localhost:27017"

[db.menu] # 이중매핑구조 map[string]map[string]interface{}
model = "menu"

[db.orderedlist]
model = "orderedlist"
