[server]
mode = "dev"
port = ":8080"
dbname = "order-system"
host = "mongodb://localhost:27017"

[db.menu] # 이중매핑구조 map[string]map[string]interface{}
model = "menu"

[db.orderedlist]
model = "orderedlist"

[log] ## normal type
level = "debug" # debug or info
fpath = "./logs/go-loger" # 로그가 생성될 경로 : ./logs, 로그파일명 go-loger_xxx.log
msize = 2000 # 2g : megabytes
mage = 7 # 7days
mbackup = 5 # number of log files